### ISSUE TITLE
What is the connection between DIPS-PLUS:1uxm.pdb1_0 and MASIF：1A2Y_BA_C?

### ISSUE THREAD

**Issue by orange2350** [BioinfoMachineLearning/DIPS-Plus#23]
thank you

**Comment by rubenalv** [comment]
@orange2350, 1A2Y_BA_C is just text, and tells MASIF to work with two chains named "BA" and "C" that are stored in separate pdb files called 1A2Y_BA.pdb and 1A2Y_C.pdb. To work with dmasif, I extracted the data from the curated .dill files and converted it to pdb, instead of recreating the full DIPS to a stage of curated pdbs.

**Comment by orange2350** [comment]
@rubenalv Thank you very much for your detailed reply.I understand now, thank you very much：）！！
